Dynamic queue sharding
secomind/mississippi pull request #21
Opened 2024-11-21 16:33 UTC by Annopaolo

Use Horde's `process_redistribution` flag to enable automatic sharding (and resharding) of processes on cluster events, e.g. a new node coming up.
This allows for autoscaling almost seamlessy (processes will be terminated and restarted on different Erlang nodes).

Based, based on #15

2025-01-14 15:12 UTC, Annopaolo commented on lib/consumer/amqp_data_consumer/starter.ex
> +  end
Not so sure here of what's the best naming, if `args`, `queue_config`, `queues_config` or something else

2025-01-21 11:32 UTC, noaccOS requested changes

2025-01-21 11:32 UTC, noaccOS commented on lib/consumer/amqp_data_consumer_supervisor.ex
> +  use Horde.DynamicSupervisor
With the changes in this module I think `AMQPDataConsumer.Supervisor` does not really have a reason to exist anymore as it is now.

I suggest we instead declare the supervisor directly in `ConsumersSupervisor` (just like `MessageTracker.Supervisor`), then we can have a single module (`AMQPDataConsumer.Starter`? I'm not too sold on the naming) to handle the children

2025-01-21 11:32 UTC, noaccOS commented on lib/consumer/amqp_data_consumer_supervisor.ex
> +    for queue_index <- 0..(queue_total - 1) do
```suggestion
    max_index = queue_total - 1

    for queue_index <- 0..max_index do
```

nit: makes the code easier on the eyes IMO

2025-01-21 11:32 UTC, noaccOS commented on lib/consumer/consumers_supervisor.ex
> +                This option is deprecated and will be ignored.
As these options have been deprecated, I think we should also remove them from `test/integration/end_to_end.exs:38`

2025-01-21 11:32 UTC, noaccOS commented on lib/consumer/amqp_data_consumer/starter.ex
> +        start_consumers(args, retry - 1)
I know it's idempotent, but in my mind you can't possibly have all the children already started right after calling `start_children` and this is bound to fail.

How about switching up the order instead to first check and then start if needed?

```suggestion
    queue_total = args[:total_count]

    child_count =
      AMQPDataConsumer.Supervisor |> DynamicSupervisor.which_children() |> Enum.count()

    case child_count do
      ^queue_total ->
        :ok

      _ ->
        AMQPDataConsumer.Supervisor.start_children(args)
        # TODO: do we want something more refined, e.g. exponential backoff?
        Process.sleep(:timer.seconds(2))
        start_consumers(args, retry - 1)
```

2025-01-21 11:32 UTC, noaccOS commented on lib/consumer/amqp_data_consumer/starter.ex
> +  end
As it is now, I suggest `queues_config`  for consistency.
However, I'm not against other namings, as long as it's consistent with other parts of the code (in the supervisor mainly)

2025-01-21 11:32 UTC, noaccOS commented on lib/consumer/node_listener.ex
> +defmodule NodeListener do
1. This module is missing the copyright
2. If we're going through the burden of having a NodeListener anyway, I think we may as well also set the members of the Horde processes ourselves. This would give us _slight_ better efficiency as we have 1 listener process instead of 6, and we may also have better consistency with cluster membership as there is only one listener process controlling it for all horde processes

2025-01-21 11:32 UTC, noaccOS commented on lib/consumer/amqp_data_consumer/starter.ex
> +        # TODO: do we want something more refined, e.g. exponential backoff?
Possibly even with some randomness so that we avoid all nodes performing these checks in sync

2025-01-29 15:04 UTC, Annopaolo commented on lib/consumer/consumers_supervisor.ex
> +                This option is deprecated and will be ignored.
I would leave them there until they are removed

2025-02-06 17:19 UTC, Annopaolo commented on lib/consumer/node_listener.ex
> +defmodule NodeListener do
After IRL discussion, we decided to keep it as is (copyright aside)

2025-02-06 17:21 UTC, Annopaolo commented on lib/consumer/amqp_data_consumer/starter.ex
> +        start_consumers(args, retry - 1)
Slightly refactored the code; now ` start_amqp_consumers(queues_config)` contains a (blocking) `Enum.each` call that waits until all children are started. Therefore I think this comment is superseded

2025-02-07 16:09 UTC, noaccOS approved these changes

2025-03-06 16:37 UTC, merged